name: Deploy to Local K8s

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t my-app:latest .

    - name: Check Kubernetes Context
      run: kubectl config current-context

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f Service.yaml
        kubectl rollout restart deployment/my-web-deployment

    - name: Verify
      run: kubectl get pods -o wide
